apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextbook
    tier: db
  name: nextbook-mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: nextbook
    tier: db
