kind: Deployment
apiVersion: apps/v1
metadata:
  name: nextbook-mongodb
  labels:
    app: nextbook
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextbook
      tier: db
  template:
    metadata:
      labels:
        app: nextbook
        tier: db
    spec:
      containers:
        - name: mongo
          image: mongo:4
          ports:
            - containerPort: 27017