apiVersion: skaffold/v2beta19
kind: Config
build:
  artifacts:
  - image: nextbook-backend
    context: src/backend
    docker:
      dockerfile: Dockerfile
      target: test
  - image: nextbook-frontend
    context: src/frontend
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/*.yaml
profiles:
- name: dev
  build:
    artifacts:
    - image: nextbook-backend
      context: src/backend
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        infer:
        - '*.py'
    - image: nextbook-frontend
      context: src/frontend
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
- name: test
  test:
  - image: nextbook-backend
    structureTests:
    - ./structure-test/backend-test.yaml
  - image: nextbook-frontend
    structureTests:
    - ./structure-test/frontend-test.yaml
