apiVersion: skaffold/v2beta22
kind: Config
build:
  artifacts:
  - image: nextbook-backend
    context: src/backend
    sync:
      infer:
      - '*.py'
  - image: nextbook-frontend
    context: src/frontend
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/*.service.yaml
    - ./kubernetes-manifests/*.deployment.yaml
profiles:
- name: prod
  test:
  - image: nextbook-backend
    structureTests:
    - ./structure-test/backend-test.yaml
  - image: nextbook-frontend
    structureTests:
    - ./structure-test/frontend-test.yaml
